### ISSUE TITLE
Get linting working with .stylelintrc

### ISSUE THREAD

**Issue by chris-pearce** [campaignmonitor/shell#17]
Already been solved as part of CM's general architecture tooling, will adopt it to Shell.

**Comment by DaveOrDead** [comment]
https://github.com/campaignmonitor/shell/pull/60

**Comment by DaveOrDead** [comment]
Keeping this issue open for clean up task.

I have actually done the cleanup, but there are some anomolies:
1. Sometimes `//` isn’t valid - but sometimes it’s fine with it.
2. Strings should be `'` not `"`
3. In settings a lot of them are over 80 chars because of long variable names
4. doesn’t like the `$shell-g-textual-inputs` string being broken over several lines
5. doesn’t like this syntax: `#{$shell-g-textual-inputs}`

I'm not sure if these are all supposed to be issues or not

**Comment by chris-pearce** [comment]
Fixed in #70.
