### ISSUE TITLE
Variable naming discrepancy

### ISSUE THREAD

**Issue by bnhovde** [campaignmonitor/shell#51]
I've started using shell in a few projects now, and one of the things I've come across that threw me was the different naming variants for scales. (the `base` keyword on spacing for example)

Example: 

```
$shell-g-font-size-heading-small
$shell-g-font-size-heading
$shell-g-font-size-heading-large

$shell-g-spacing-small
$shell-g-spacing-base
$shell-g-spacing-large

$shell-container-maximum-width-small
$shell-container-maximum-width
$shell-container-maximum-width-large
```

I'm used to the difference now, but I imagine new adopters will find this annoying too as the `spacing` variable is the only scale that includes the `base` word.

> Why the f**\* is it not compiling?!
> - Me

**Disclaimer:** I may not use shell in the way it was designed to be used. I never use any of the scaling helper classes. If i need to scale an element (either font-size, font-weight, padding, margin etc) that element will be part of a module, and so I'll be using the SASS variable `$shell-g-font-size-heading-large` rather than the `heading heading--large` helper classes.

**Comment by DaveOrDead** [comment]
Good spot on spacing-base.

Are there any others? We've tried to make them consistent so this would have just been an oversight.

I'm in favour of ditching -base rather than adding it to the others.

With regards to the helper classes, the main use case is using 'h-spacing-whatever' to do vertical spacing (margin-bottom) between components. We aim to never bake margins into components so that they can be dropped anywhere and work.

Sounds like you're using it right though, the helpers are really a last resort. Variables would be the first port of call

**Comment by bnhovde** [comment]
Cool! Not a big issue really. Glad to hear we're using it in the same way.

Loving everything else!

**Comment by chris-pearce** [comment]
@bnhovde thanks for the feedback 👍 .

I think ditching it for the spacing setting makes sense, so it's just `$shell-g-spacing`. We use **base** in other places to though e.g. 
- https://github.com/campaignmonitor/shell/blob/master/src/_settings.scss#L101-L105
- https://github.com/campaignmonitor/shell/blob/master/src/_settings.scss#L167-L168
- https://github.com/campaignmonitor/shell/blob/master/src/_settings.scss#L608-L614
- https://github.com/campaignmonitor/shell/blob/master/src/_settings.scss#L726-L732

See #52.

**Comment by DaveOrDead** [comment]
I guess the helper should be `h-spacing` then as well?

**Comment by DaveOrDead** [comment]
Fixed in PR https://github.com/campaignmonitor/shell/pull/53
