### ISSUE TITLE
Use `v` units in place of `%` where we can

### ISSUE THREAD

**Issue by chris-pearce** [campaignmonitor/shell#7]
E.g. `l-container`.

**Comment by DaveOrDead** [comment]
Chris W said the other day `vw` units were less performant than `%` for layout - could be worth double checking with him before implementing.

Performance aside though, where `l-container` is often used inside of say a main app area, I'd have thought sizing it relative to the viewport using `v` units rather than it's parent might not be advisable.  Probably best sticking with `%` for this?

**Comment by chris-pearce** [comment]
Interesting re performance, if that is the case I'd say it won't be a problem for long.

But yeah you're right in that `%` is the most appropriate unit to use anyway as the `vw` unit would only be applicable to the parent most containers i.e. the ones that are relative to the viewport.

I'll close this.
